# Generated by Django 3.2.4 on 2021-06-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('commandor', models.CharField(max_length=50, verbose_name='Руководитель')),
                ('Inn', models.CharField(max_length=17, verbose_name='ИНН')),
                ('adress', models.CharField(max_length=50, verbose_name='Адресс')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('parking', models.IntegerField(default=100, verbose_name='Парк.места')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
    ]
