# Generated by Django 3.2.4 on 2021-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210607_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='client',
            name='bankname',
            field=models.CharField(default='', max_length=25, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='client',
            name='banknumber',
            field=models.CharField(default='', max_length=20, verbose_name='БанковскийСчёт'),
        ),
        migrations.AddField(
            model_name='client',
            name='fullname',
            field=models.CharField(default='', max_length=50, verbose_name='ПолноеИмя'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport',
            field=models.CharField(default='', max_length=10, verbose_name='Паспорт'),
        ),
        migrations.AddField(
            model_name='client',
            name='sign',
            field=models.CharField(default='', max_length=10, verbose_name='ЮридическийПризнак'),
        ),
    ]
